// this code is autogenerated, do not check it into to your code repository

// ref lib/nif_naive_state.ex:4
const beam = @import("beam");
var stored:i64 = 0;

pub fn new(value: i64) void {
  stored = value;
}

pub fn get(_: beam.term) i64 {
  return stored;
}

pub fn put(_: beam.term, value: i64) void {
  stored = value;
}
