// this code is autogenerated, do not check it into to your code repository

// ref lib/nif_resource_state.ex:4
pub const I64Res = 
  @import("beam").Resource(i64, @import("root"), .{});

pub fn new(value: i64) !I64Res {
  return I64Res.create(value, .{});
}

pub fn get(resource: I64Res) i64 {
  return resource.unpack();
}

pub fn put(resource: I64Res, new_value: i64) void {
  resource.update(new_value);
}
